package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public final class Account implements org.omg.CORBA.portable.IDLEntity
{
  public String first = null;
  public String last = null;
  public String email = null;
  public String institution = null;
  public String telephone = null;

  public Account ()
  {
  } // ctor

  public Account (String _first, String _last, String _email, String _institution, String _telephone)
  {
    first = _first;
    last = _last;
    email = _email;
    institution = _institution;
    telephone = _telephone;
  } // ctor

} // class Account
