package ca.concordia.drms.orb;

/**
* ca/concordia/drms/orb/BookHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public final class BookHolder implements org.omg.CORBA.portable.Streamable
{
  public ca.concordia.drms.orb.Book value = null;

  public BookHolder ()
  {
  }

  public BookHolder (ca.concordia.drms.orb.Book initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.concordia.drms.orb.BookHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.concordia.drms.orb.BookHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.concordia.drms.orb.BookHelper.type ();
  }

}
