package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/Book.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public final class Book implements org.omg.CORBA.portable.IDLEntity
{
  public String title = null;
  public String author = null;
  public String code = null;

  public Book ()
  {
  } // ctor

  public Book (String _title, String _author, String _code)
  {
    title = _title;
    author = _author;
    code = _code;
  } // ctor

} // class Book
