package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/LibraryServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public interface LibraryServer extends LibraryServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryServer
