package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/LibraryServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public interface LibraryServerOperations 
{

  /**
  						 * Function that creates an account if the account does not exists 
  						 * @param first
  						 * @param last
  						 * @param email
  						 * @param telephone
  						 * @param username
  						 * @param password
  						 * @param institution
  						 */
  void createAccount (String first, String last, String email, String telephone, String username, String password, String institution) throws ca.concordia.drms.orb.RemoteException;

  /**
  						 * This function checks current library, to reserve a book
  						 * @param username
  						 * @param password
  						 * @param title
  						 * @param author
  						 */
  void reserveBook (String username, String password, String title, String author) throws ca.concordia.drms.orb.RemoteException;

  /**
  						 * This function checks current library, to reserve a book
  						 * @param username
  						 * @param password
  						 * @param title
  						 * @param author
  						 */
  void reserveInterLibrary (String username, String password, String title, String author) throws ca.concordia.drms.orb.RemoteException;

  /**
  						 * uses messages to send back and forth stream of info 
  						 * @param <V>
  						 * @param <K>
  						 * @param username
  						 * @param password
  						 * @param institution
  						 * @param days
  						 * @return
  						 */
  ca.concordia.drms.orb.Reservation[] getNonReturners (String username, String password, String institution, int days) throws ca.concordia.drms.orb.RemoteException;

  /**
  						 * 
  						 * @param username
  						 * @param title
  						 * @param days
  						 * @throws RemoteException
  						 */
  void setDuration (String username, String title, int days) throws ca.concordia.drms.orb.RemoteException;
} // interface LibraryServerOperations
