package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/LibraryServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

abstract public class LibraryServerHelper
{
  private static String  _id = "IDL:ca/concordia/drms/orb/LibraryServer:1.0";

  public static void insert (org.omg.CORBA.Any a, ca.concordia.drms.orb.LibraryServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ca.concordia.drms.orb.LibraryServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ca.concordia.drms.orb.LibraryServerHelper.id (), "LibraryServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ca.concordia.drms.orb.LibraryServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibraryServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ca.concordia.drms.orb.LibraryServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ca.concordia.drms.orb.LibraryServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ca.concordia.drms.orb.LibraryServer)
      return (ca.concordia.drms.orb.LibraryServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ca.concordia.drms.orb._LibraryServerStub stub = new ca.concordia.drms.orb._LibraryServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ca.concordia.drms.orb.LibraryServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ca.concordia.drms.orb.LibraryServer)
      return (ca.concordia.drms.orb.LibraryServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ca.concordia.drms.orb._LibraryServerStub stub = new ca.concordia.drms.orb._LibraryServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
