package ca.concordia.drms.orb;

/**
* ca/concordia/drms/orb/RemoteExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public final class RemoteExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ca.concordia.drms.orb.RemoteException value = null;

  public RemoteExceptionHolder ()
  {
  }

  public RemoteExceptionHolder (ca.concordia.drms.orb.RemoteException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.concordia.drms.orb.RemoteExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.concordia.drms.orb.RemoteExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.concordia.drms.orb.RemoteExceptionHelper.type ();
  }

}
