package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/RemoteException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public final class RemoteException extends org.omg.CORBA.UserException
{
  public String message = null;

  public RemoteException ()
  {
    super(RemoteExceptionHelper.id());
  } // ctor

  public RemoteException (String _message)
  {
    super(RemoteExceptionHelper.id());
    message = _message;
  } // ctor


  public RemoteException (String $reason, String _message)
  {
    super(RemoteExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class RemoteException
