package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/Reservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

public final class Reservation implements org.omg.CORBA.portable.IDLEntity
{
  public ca.concordia.drms.orb.Account account = null;
  public ca.concordia.drms.orb.Book book = null;
  public int fees = (int)0;

  public Reservation ()
  {
  } // ctor

  public Reservation (ca.concordia.drms.orb.Account _account, ca.concordia.drms.orb.Book _book, int _fees)
  {
    account = _account;
    book = _book;
    fees = _fees;
  } // ctor

} // class Reservation
