package ca.concordia.drms.orb;


/**
* ca/concordia/drms/orb/ReservationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from drms.idl
* Saturday, November 15, 2014 2:44:03 PM EST
*/

abstract public class ReservationHelper
{
  private static String  _id = "IDL:ca/concordia/drms/orb/Reservation:1.0";

  public static void insert (org.omg.CORBA.Any a, ca.concordia.drms.orb.Reservation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ca.concordia.drms.orb.Reservation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = ca.concordia.drms.orb.AccountHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "account",
            _tcOf_members0,
            null);
          _tcOf_members0 = ca.concordia.drms.orb.BookHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "book",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "fees",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ca.concordia.drms.orb.ReservationHelper.id (), "Reservation", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ca.concordia.drms.orb.Reservation read (org.omg.CORBA.portable.InputStream istream)
  {
    ca.concordia.drms.orb.Reservation value = new ca.concordia.drms.orb.Reservation ();
    value.account = ca.concordia.drms.orb.AccountHelper.read (istream);
    value.book = ca.concordia.drms.orb.BookHelper.read (istream);
    value.fees = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ca.concordia.drms.orb.Reservation value)
  {
    ca.concordia.drms.orb.AccountHelper.write (ostream, value.account);
    ca.concordia.drms.orb.BookHelper.write (ostream, value.book);
    ostream.write_long (value.fees);
  }

}
